routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/view_document/{document}', 'HomeController@viewDocument')->name('view_document');

Route::get('/admin', 'Auth\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('/admin', ['as'=> 'admin-login','uses'=>'Auth\AdminLoginController@login']);

Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/home', 'Admin\DashboardController@index' )->name('index');
		Route::get('/show_document', 'Admin\DashboardController@showDocument')->name('show_document');
		Route::post('/add_doc', 'Admin\DashboardController@uploadDocument' )->name('add_doc');
		Route::get('/destroy_document/{document}', 'Admin\DashboardController@destroyDocument' )->name('destroy_document');
		

		// agents
		Route::get('/show_agents', 'Admin\DashboardController@showAgents')->name('show_agents');
		Route::post('/add_agent', 'Admin\DashboardController@addAgent' )->name('add_agent');
		Route::get('/destroy_agent/{agent}', 'Admin\DashboardController@destroyAgent' )->name('destroy_agent');





		// Déconnexion prof
		Route::post('/admin-logout',function(){
			auth()->logout();
			return redirect()->route('admin-login');
		})->name('logout');
	});





	
});

resources/views/home.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')

<div class="row d-flex justify-content-center">
    <div class="col-10">
        <div class="card">

            {{-- <div class="card-header">DDDDD</div> --}}
            <div class="card-body bg-dark text-white">
                @auth('admin')
                <div class="row">
                    <div class="col">
                        <!-- Button trigger modal -->
                        <button href="{{ route('admin.add_doc') }}" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
                          <i class="fa fa-plus"></i> Nouveau document
                        </button>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content bg-dark">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ajouter un doucument</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body ">
                        @include('partials._msgFlash')
                           <form  method="POST" id="myForm" action="{{ route('admin.add_doc') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                              <label for="titre">Titre</label>
                              <input type="text" class="form-control" id="titre" placeholder="" name="titre" value="{{ old('titre') }}" required="">
                            </div>
                            <div class="form-group">
                              <label for="description">Description</label>
                              <input type="text" class="form-control" id="description" placeholder="" name="description" value="{{ old('description') }}" required="">
                            </div>
                            <div class="form-group">
                            <label for="iddepartement">Departement</label>
                            <select class="form-control" id="iddepartements" required="" name="iddepartements" required="">
                              @foreach(App\Models\Departement::get() as $d)
                              <option value="{{ $d->iddepartements }}">{{ $d->lib }}</option>
                              @endforeach
                            </select>
                          </div>
                          <label for="description">Importer le fichier</label>
                          <div class="custom-file">
                              <input type="file" class="custom-file-input" id="doc-file" name="document"required>
                              <label class="custom-file-label" for="doc-file">Choisir un fichier pdf</label>
                            </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                      </div>
                       </form>
                      {{-- <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                      </div> --}}
                    </div>
                  </div>
                </div>








                @endauth
                 {!!$dataTable->table() !!}
            </div>
        </div>
    </div>
</div>
    

@endsection
@push('scripts')
  {!!$dataTable->scripts() !!}
  <script type="text/javascript">
   
    // $(document).on('submit', '#myForm', function(e) {
    //     e.preventDefault();
    //     alert($('#doc-file').val());
    //     $('#msgErrors').attr('hidden',true);
    //     // var myForm = new FormData();
    //     // myForm.append($(this).serialize());
    //     // myForm.append("document", $('#doc-file').val());
    //     $.ajaxSetup({
    //         headers: {
    //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //         }
    //     });
    //     $.ajax({
    //             method: 'POST',
    //             url: $(this).attr('action'),
    //             data: {
    //                 '_token': $('input[name=_token]').val(),
    //                 'titre': $("#titre").val(),
    //                 'description': $("#description").val(),
    //                 'iddepartements': $('#iddepartements').val(),
    //                 'document': $('#doc-file').val(),
    //                 },
    //             // processData: false,
    //             // contentType: false,
    //             success: function(data) {
    //                 if (data == "uploaded") {
    //                    alert('OOOOOOOOOOOOOOOOOOOOO');
    //                    $('#dataTableBuilder').DataTable().draw(false);
    //                    $('.modal').modal('hide');
    //                 } else {
    //                     var errors = data.responseJSON.errors;
    //                     $.each(errors, function (key, value) {
    //                       document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
    //                       $('#msgErrors').attr('hidden',false);
    //                   });
    //                 }
    //             },
    //             error: function(error) {
    //                 console.log(error);
    //                 var errors = error.responseJSON.errors;
    //                     $.each(errors, function (key, value) {
    //                       document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
    //                       $('#msgErrors').attr('hidden',false);
    //                   });
    //             }
    //         });
    // });
  </script>
@endpush

resources/views/view_document.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

        <!-- Custom CSS -->
    <link href="{{ asset('backend/dist/css/style.min.css') }}" rel="stylesheet">
     <link href="{{ asset('dataTables/dataTables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dataTables/buttons/css/buttons.dataTables.min.css') }}" rel="stylesheet">

  </head>

  <body class="bg-dark">
    <div class="card">
        <div class="card-header bg-danger">
        @auth('admin')
        <a href="{{ route('admin.show_document') }}" class="text-white">retour</a>
        @endauth
        @auth('web')
        <a href="{{ route('home') }}" class="text-white">retour</a>
        @endauth
        
        @auth('web')
        <h5 class="h3 card-title text-center text-monospace text-white">{{ App\Models\Departement::find(auth()->user()->iddepartements)->lib }}</h5>
        @endauth
        </div>
    </div>
    <div id="document" style="margin-top: -20px"></div>

    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>
    <!-- <script src="dist/js/jquery.ui.touch-punch-improved.js"></script>
    <script src="dist/js/jquery-ui.min.js"></script> -->
    <!-- Bootstrap tether Core JavaScript -->
    <script src={{ asset('backend/assets/libs/popper.js/dist/umd/popper.min.js') }}></script>
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('js/pdfObject.js') }}></script>
    <script>
      var options = {
        height: "600px",
        // pdfOpenParams: { view: 'FitV', page: '2' }
    };
      PDFObject.embed("{{ url(Storage::url($document->file)) }}", "#document",options);
    </script>

  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/floating-labels/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:42:06 GMT -->
</html>