routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/view_document/{document}', 'HomeController@viewDocument')->name('view_document');

Route::get('/admin', 'Auth\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('/admin', ['as'=> 'admin-login','uses'=>'Auth\AdminLoginController@login']);

Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/home', 'Admin\DashboardController@index' )->name('index');
		Route::get('/show_document', 'Admin\DashboardController@showDocument')->name('show_document');
		Route::post('/add_doc', 'Admin\DashboardController@uploadDocument' )->name('add_doc');
		Route::get('/destroy_document/{document}', 'Admin\DashboardController@destroyDocument' )->name('destroy_document');
		

		// agents
		Route::get('/show_agents', 'Admin\DashboardController@showAgents')->name('show_agents');
		Route::post('/add_agent', 'Admin\DashboardController@addAgent' )->name('add_agent');
		Route::get('/destroy_agent/{agent}', 'Admin\DashboardController@destroyAgent' )->name('destroy_agent');





		// Déconnexion prof
		Route::post('/admin-logout',function(){
			auth()->logout();
			return redirect()->route('admin-login');
		})->name('logout');
	});





	
});

resources/views/admin/index.blade.php
@extends('layouts.master')
@section('content')
<div class="card bg-transparent" style=" margin-top: 10%;">
  {{-- <div class="card-header">
    Quote
  </div> --}}

  <div class="card-body">
    <div class="row">
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <button type="button" class="addModal btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
			    	<h5 class="card-title " ><i class="fas fa-plus-circle fa-2x"></i></h5>
			    	<h5 class="card-text">NOUVEAU DOCUMENT</h5>
			    </button>
			  </div>
			</div>
    	</div>
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <a href="{{ route('admin.show_document') }}" class="btn btn-primary">
			    	<h5 class="card-title " ><i class=" fas fa-archive fa-2x"></i></h5>
			    	<h5 class="card-text">ARCHIVES DOCUMENTS</h5>
			    </a>
			  </div>
			</div>
    	</div>
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <a href="{{ route('admin.show_agents') }}" class="btn btn-primary">
			    	<h5 class="card-title " ><i class=" fas fa-user fa-2x"></i></h5>
			    	<h5 class="card-text">AGENTS</h5>
			    </a>
			  </div>
			</div>
    	</div>
    	
    </div>
  </div>

</div>
@include('partials.includes.formulaires._add_document_modal')

@endsection

resources/views/admin/show_agent.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')

<div class="row d-flex justify-content-center">
    <div class="col-10">
        <div class="card">

            {{-- <div class="card-header">DDDDD</div> --}}
            <div class="card-body bg-dark text-white">
                @auth('admin')
                <div class="row">
                    <div class="col">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
                          <i class="fa fa-plus"></i> Nouveau Agent
                        </button>
                    </div>
                </div>
                @include('partials.includes.formulaires._add_agent_modal')
                @endauth
                 {!!$dataTable->table() !!}
            </div>
        </div>
    </div>
</div>



@endsection
@push('scripts')
  {!!$dataTable->scripts() !!}
  
@endpush

resources/views/admin/show_document.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')

<div class="row d-flex justify-content-center">
    <div class="col-10">
        <div class="card">

            {{-- <div class="card-header">DDDDD</div> --}}
            <div class="card-body bg-dark text-white">
                @auth('admin')
                <div class="row">
                    <div class="col">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
                          <i class="fa fa-plus"></i> Nouveau document
                        </button>
                    </div>
                </div>
                @include('partials.includes.formulaires._add_document_modal')
                @endauth
                 {!!$dataTable->table() !!}
            </div>
        </div>
    </div>
</div>
    

@endsection
@push('scripts')
  {!!$dataTable->scripts() !!}
  
@endpush