routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/view_document/{document}', 'HomeController@viewDocument')->name('view_document');

Route::get('/admin', 'Auth\AdminLoginController@showLoginForm')->name('admin-login');
Route::post('/admin', ['as'=> 'admin-login','uses'=>'Auth\AdminLoginController@login']);

Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/home', 'Admin\DashboardController@index' )->name('index');
		Route::get('/show_document', 'Admin\DashboardController@showDocument')->name('show_document');
		Route::post('/add_doc', 'Admin\DashboardController@uploadDocument' )->name('add_doc');
		Route::get('/destroy_document/{document}', 'Admin\DashboardController@destroyDocument' )->name('destroy_document');
		

		// agents
		Route::get('/show_agents', 'Admin\DashboardController@showAgents')->name('show_agents');
		Route::post('/add_agent', 'Admin\DashboardController@addAgent' )->name('add_agent');
		Route::get('/destroy_agent/{agent}', 'Admin\DashboardController@destroyAgent' )->name('destroy_agent');





		// Déconnexion prof
		Route::post('/admin-logout',function(){
			auth()->logout();
			return redirect()->route('admin-login');
		})->name('logout');
	});





	
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>
    <!-- Fonts -->
    {{-- <link href = "https://fonts.googleapis.com/css?family= Roboto " rel = "stylesheet"> --}}
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    {{-- Styles --}}
    {{-- <link href="{{ asset('bootstrap/css/style.css') }}" rel="stylesheet"> --}}
    <style type="text/css">
        body{
            margin: 5%;
            background-image: url({{ asset('img/cover.jpg')}});
            background-repeat : repeat;
            background-position: center;
            background-color: #131517;
        }
        .bg-purple { background-color: #6f42c1; }
    </style>
    @yield('stylesheet')
    @stack('stylesheets')

</head>

<body class="text-monospace">
    <div class="container" style="margin-top: -50px">
      <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-danger rounded shadow-sm">
        <img class="mr-3" src="{{ asset('img/default-profil.png') }}" alt="" width="48" height="48">
        <div class="lh-100 text-monospace">
          <h6 class="mb-0 text-white lh-100">ARCHIVAGE DES DOCUMENTS</h6>
          {{-- <small>République Démocrarique du Congo</small> --}}
        </div>
      </div>
        @yield('content')
         @auth('web')
        <small class="d-block text-right mt-3">
          <a href="{{ route('home') }}">Accueil</a>
          <a href="{{ route('logout') }}"
             onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
              Déconnexion
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </small>
        @else
        @if(!auth('admin')->check())
          <small class="d-block text-right mt-3">
          {{-- <a href="/">Accueil</a> --}}
          <a href="{{ route('login') }}">Connexion</a>
        </small>
        @endif
        @endauth
        @auth('admin')
        <small class="d-block text-right mt-3">
          <a href="{{ route('admin.index') }}">Accueil</a>
          <a href="{{ route('admin.logout') }}"
             onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
              Déconnexion
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </small>
        @endauth
    </div>
     
    {{-- Container   --}}
    
    {{-- Session Flash --}}
    @yield('msg_flash')
    <footer class="footer">
        @yield('footer')
        <script src="{{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}"></script>
        <!-- <script src="dist/js/jquery.ui.touch-punch-improved.js"></script>
        <script src="dist/js/jquery-ui.min.js"></script> -->
        <!-- Bootstrap tether Core JavaScript -->
        <script src="{{ asset('backend/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="{{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
         {{-- <script type="text/javascript" src="{{ asset('dataTables/datatables.min.js') }}"></script> --}}
        @yield('script')
        @stack('scripts')
        @include('flashy::message')

    </footer>
</body>
</html>